### PR TITLE
Create system to update sources and dependencies

### PR DESCRIPTION
**Pull request by grillo-delmal**
This is based on the update script present in the [org.flozz.calcleaner project](https://github.com/flathub/org.flozz.calcleaner/blob/master/update-dependencies.sh). In it's current state it can generate dependency lists that can build the version of inochi-creator detected on the yaml file.

### Verification stage
* Extract the commit hash from the `./com.inochi2d.inochi-creator.yml` file (`checkout target`)
  * You can skip this part by passing the `--target=<string>` parameter and pass a specific `checkout target`
* The next part of the process can be skipped if you use the `-f/--force` argument.
  * If it's not a nightly build and a `.dep_target` file exists.
    * Extract the commit hash from `.dep_target`.
    * If both hashes are the same, then the process exits with err code 1.

### Download Stage
* Clears the working folder (`./dep.build`).
* Clones inochi-creator repository.
* Checkouts the commit hash from the `checkout target`.
* Clones all the forked repositories into the deps folder.
* If its not a nightly build, then it sincronizes the deps with the inochi-creator repo through the following steps.
  * Checkout the latest tag for inochi-creator.
  * Check the date from inochi-creator's latest tag head.
  * For each repo find the latest commit before the date of the latest tag's head.
  * Checkout that commit.
* Fix the tag for inochi2d if it's broken.
* Checkout semver version required for gitver.

### Build Stage
* Add all the forked repositories as local dependencies for the inochi-creator project.
* Run `dub describe` to download the dependencies and list the required versions on `dub.selections.json`.

### Process Stage
* Get `flatpak-dub-generator.py` from [flatpak-builder-tools](https://github.com/flatpak/flatpak-builder-tools).
* Run through the processed `dub.selections.json` to generate `dub-add-local-sources.json`.
  * Adds the gitver and semver repositories.
  * Replace all the forked libraries with the propper git repositories and commit hashes.
* If it's a nightly build, it will remove the `.dep_target` file.
  * If its not, it will store the `checkout target` to the `.dep_target` file.

### CODE REVIEW

**Comment by orowith2os** [comment]
More comments, and the split of Inochi-creator (or add it as a fake source) would still be nice to have, so that the repository can update on its own.

**Comment by orowith2os** [comment]
I find the layout of the scripts hard to understand. I added some comments about what I don't get, but I don't like it at all. Reading it, I had tons of "what does this do?" And "huh?" Moments.

**Comment by orowith2os** [comment]
I meant have the inochi-creator source be in the main manifest, if it's in its separate sources file, it might as well be in the normal dependencies list.

**Comment by grillo-delmal** [comment]
> I meant have the inochi-creator source be in the main manifest, if it's in its separate sources file, it might as well be in the normal dependencies list.

I separated it in another file because it's easier to parse the commit hash for resolving dependencies of that specific version. If this information would be in the yaml file, I would need to use a yaml parser to actually find out what commit hash I need to verify.

**Comment by orowith2os** [comment]
Mm, alright, maybe it should be a separate fake source then. I'll make a suggestion that you can apply in a moment.

**Comment by grillo-delmal** [comment]
I restructured things a bit considering what we talked. I changed the yaml file, adding the inochi-creator source and the `x-checker-data` entry so that it updates correctly.

Also modified the script so that it updates the dependency list considering the commit hash inside the yaml file so that it's easy to create a workflow to automate the process.

**Comment by grillo-delmal** [comment]
I created a workflow to trigger this script whenever there is a commit on the main branch that modifies the yaml file, it follows up with a new commit that adds the dependency changes... don't know if I should add it to this PR since it's already a bulky one, so for now i'll just copy it here for you to review for now.

```yaml
name: Update deps

on:
  push:
    branches:
      - main
    paths:
      - 'com.inochi2d.inochi-creator.yml'

jobs:
  update:
    runs-on: freedesktop-22.08
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-22.08
      options: --privileged
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo dnf -y install dub ldc python3-pyyaml

      - name: Create and switch to working branch
        run: git switch -c update-dub-modules-$(git rev-parse --short HEAD)

      - name: Run dependency update script
        run: |
          set -e
          export DC='/usr/bin/ldc2'
          ./update-dependencies.sh
          if test $? -eq 0
          then
            git add -- dub-add-local-sources.json .dep_target
            git commit -m "Update dependencies"
            git push https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}
          fi
```

**Comment by orowith2os** [comment]
Sorry, one more bit to add here: could you run the external data checker in the workflow too? That way we get two birds with one stone.

**Comment by grillo-delmal** [comment]
> Sorry, one more bit to add here: could you run the external data checker in the workflow too? That way we get two birds with one stone.

Just to be clear, we have 2 options here.
1) Reactive one: 
* Don't implement the data checker in the workflow
* Let the automatic flatpak bot process run the data checker on our file and push a commit that will generate a failed build
* Let the workflow react to that commit and generate a new commit with the updated dependencies that will result in a successfull build (hopefully)

2) Proactive one
* Implement the data checker in the workflow
* Block the flatpack bot so it doesn't run the data checker
* Run the workflow periodically (once an hour? once a day?) or manually to generate the new version.

The workflow I created here is the reactive one. What you want is the second one, right?

**Comment by orowith2os** [comment]
Correct. If we have the workflow running here manually, we'll already be set up for Flathub Beta builds, as the bot doesn't check non-default branches.

**Comment by grillo-delmal** [comment]
> Correct. If we have the workflow running here manually, we'll already be set up for Flathub Beta builds, as the bot doesn't check non-default branches.

I was expecting either way to do a different workflow for beta builds (since nightlies aren't reactive by definition xD). I'll do workflows in different branches since this PR already has lot's of stuff.

**Comment by orowith2os** [comment]
> I'll do workflows in different branches since this PR already has lot's of stuff.

Sounds good. Does this PR look good to you to merge otherwise?

**Comment by grillo-delmal** [comment]
I think it's done :+1: 
If you have any questions or want me to give you a rundown on how everything works in detail, I'm available in DMs or a voice call if you need to ;)

**Pull request merged**
